name: Data Review Submission
description: Review an existing technique tag or suggest a new one
title: "[Tag] "
labels: ["data-review"]
body:
  - type: markdown
    attributes:
      value: |
        **Tip:** For a better experience, use the [Tag & Review tool](https://sashaagafonoff.github.io/LLM-Safety-Mechanisms/tag) which pre-fills this form for you.

  - type: dropdown
    id: action
    attributes:
      label: Action
      options:
        - add_new_tag
        - delete_tag
        - link_evidence
    validations:
      required: true

  - type: input
    id: source_id
    attributes:
      label: Source ID
      description: "Source document identifier from evidence.json (e.g., gpt-5-system-card)"
      placeholder: gpt-5-system-card
    validations:
      required: true

  - type: input
    id: technique_id
    attributes:
      label: Technique ID
      description: "Technique identifier from techniques.json (e.g., tech-rlhf)"
      placeholder: tech-rlhf
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence Text
      description: Quote specific text from the source document that supports this tag
      placeholder: Paste the relevant excerpt here...
    validations:
      required: true

  - type: input
    id: github_username
    attributes:
      label: GitHub Username
      description: "Your GitHub username for attribution"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Optional notes or explanation
