name: Daily Evidence Automation

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install openai  # Add to requirements.txt
    
    - name: Run automation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python scripts/daily_automation.py
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: automated evidence updates'
        title: '[Automated] Daily Evidence Updates'
        body: |
          ## 🤖 Automated Evidence Updates
          
          This PR contains:
          - New evidence extracted from recent sources
          - Updated source verification hashes
          - Dashboard updates
          
          Please review the changes before merging.
        branch: automated/daily-${{ github.run_number }}
        delete-branch: true