name: Weekly Source Verification

on:
  schedule:
    # Run every Monday at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  verify-sources:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install PyPDF2  # For PDF extraction
    
    - name: Run source verification
      id: verify
      run: |
        python scripts/verify_sources.py --check-new-only > verification.log 2>&1
        echo "exit_code=$?" >> $GITHUB_OUTPUT
        
        # Extract summary for PR
        tail -n 20 verification.log > verification_summary.txt
    
    - name: Check for changes
      id: changes
      run: |
        if [[ -n $(git status -s data/) ]]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Pull Request
      if: steps.changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update source verification hashes'
        title: '[Automated] Weekly Source Verification Update'
        body: |
          ## 🔍 Weekly Source Verification Results
          
          This automated PR updates source hashes based on the weekly verification run.
          
          ### Summary
          ```
          ${{ steps.verify.outputs.summary }}
          ```
          
          ### Changes
          - Updated source hashes for verified URLs
          - Updated last verification dates
          
          ### Full Log
          See the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
          
          ---
          *This PR was automatically created by the weekly verification workflow.*
        branch: automated/source-verification-${{ github.run_id }}
        delete-branch: true
        labels: |
          automated
          verification
          maintenance
    
    - name: Create issue for failures
      if: steps.verify.outputs.exit_code != '0'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('verification_summary.txt', 'utf8');
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '[Automated] Source Verification Failures Detected',
            body: `## ⚠️ Source Verification Issues
                   The weekly verification detected some failures.

                   ### Summary
                   \`\`\`
                   ${summary}
                   \`\`\`

                   ### Action Required
                   Please review the failed sources and:
                   1. Update URLs if they've moved
                   2. Remove evidence if sources are permanently unavailable
                   3. Find alternative sources if possible

                   [View Full Workflow Run]
                   (${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
        labels: ['bug', 'verification', 'help wanted']
          });